---
- name: Setup Node.js Backend
  hosts: all  # Change to your inventory group if needed
  become: yes

  tasks:
    - name: Install required packages
      apt:
        name:
          - nodejs
          - npm
          - openssl
        state: present
        update_cache: yes

    - name: Install PM2 globally
      npm:
        name: pm2
        global: yes

    - name: Create environment file
      copy:
        dest: /home/ubuntu/blog-app/backend/.env
        content: |
          PORT=5000
          HOST=0.0.0.0
          MODE=production
          # Database configuration
          MONGODB=mongodb+srv://test:qazqwe123@mongodb.txkjsso.mongodb.net/blog-app
          # JWT Authentication
          JWT_SECRET={{ lookup('pipe', 'openssl rand -hex 32') }}
          JWT_EXPIRE=30min
          JWT_REFRESH={{ lookup('pipe', 'openssl rand -hex 32') }}
          JWT_REFRESH_EXPIRE=3d
          # AWS S3 Configuration
          AWS_ACCESS_KEY_ID="YOUR_AWS_ACCESS_KEY"
          AWS_SECRET_ACCESS_KEY="YOUR_AWS_SECRET_KEY"
          AWS_REGION=eu-north-1
          S3_BUCKET=mern-media-r2osjfjd
          MEDIA_BASE_URL=mern-media-r2osjfjd.s3.eu-north-1.amazonaws.com
          # Misc
          DEFAULT_PAGINATION=20

    - name: Install npm packages
      command: pnpm install
      args:
        chdir: /home/ubuntu/blog-app/backend

    - name: Start application with PM2
      command: pm2 start index.js --name "blog-backend"
      args:
        chdir: /home/ubuntu/blog-app/backend

    - name: Save PM2 process list
      command: pm2 save


